server:
  port: 8546
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: POSTGRESQL
  datasource:
    url: jdbc:postgresql://165.227.81.33:5432/db-tienda
    username: ustiendazely
    password: T!3ND@Z3L1SmP
    driver-class-name: org.postgresql.Driver